kind: pipeline
type: kubernetes
name: Deploy Afstemning
steps:
  - name: Deploy Main Container
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl create -f afstemning-deployment.yaml