apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: afstemning
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/simcax/deploy-afstemning.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: afstemningdev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
